# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MmE5MjNmNWY5Y2VlMTEzNmJkMDlhNGZkMjFkZWEyMTVlZjkxOWYyN2FiZTYzMjU0NjM0ZjNhZTI1OTRkYmNiZmNmOTQxZGIyZGZmODZlNjY4ZDhkZmQyZjgxZmNlZDBhZjcxMWJjZmUxNmQ0NTU3N2EzNmNiYzg4YTk2NGRjZGU=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
